"""Admin backup/export constants.

The admin blueprint imports these values while the data schema stays isolated
from route handlers and page payload builders.
"""

import re

BOT_DATABASE_EXPORT_KIND = "pragtico.bot_database_export"
SYSTEM_DATABASE_EXPORT_KIND = "pragtico.system_database_export"
DATABASE_EXPORT_VERSION = 1
SYSTEM_KNOWLEDGE_ALLOWED_SUFFIXES = {".txt", ".md", ".json"}
BACKUP_MANIFEST_FILENAME = "backup_manifest.json"
BACKUP_PACKAGE_DATA_FILENAME = "backup.json"
BACKUP_PACKAGE_README_FILENAME = "README.md"
BACKUP_FILENAME_RE = re.compile(r"^pragtico-backup-\d{8}-\d{6}(?:-\d{6})?\.(?:zip|json)$")
BACKUP_AUTO_CHECK_THROTTLE_SECONDS = 60
DATABASE_WIPE_CONFIRMATION_PHRASE = "LIMPAR BASE PRAGTICO"
POSTGRES_EXPORT_TABLES = {
    "app_users": {
        "pk": ("username",),
        "jsonb": set(),
        "columns": (
            "username",
            "password_hash",
            "role",
            "full_name",
            "organization",
            "email",
            "phone",
            "whatsapp_number",
            "whatsapp_opt_in",
            "whatsapp_opt_in_at",
            "profile_completed_at",
        ),
    },
    "documents": {
        "pk": ("name",),
        "jsonb": set(),
        "columns": (
            "name",
            "original_name",
            "doc_type",
            "size_bytes",
            "updated_at",
            "created_at",
            "uploaded_by",
            "preview",
            "file_path",
        ),
    },
    "port_calls": {
        "pk": ("id",),
        "jsonb": {"maneuver_history"},
        "columns": (
            "id",
            "vessel_name",
            "vessel_short_name",
            "vessel_imo",
            "vessel_call_sign",
            "vessel_flag",
            "vessel_type",
            "vessel_loa_m",
            "vessel_beam_m",
            "vessel_gt_t",
            "vessel_max_draft_m",
            "vessel_dwt_t",
            "vessel_bow_thruster",
            "vessel_stern_thruster",
            "status",
            "approval_status",
            "approval_note",
            "aborted_reason",
            "decided_by",
            "decided_at",
            "eta",
            "ata",
            "planned_departure_at",
            "departure_plan_note",
            "departure_at",
            "planned_shift_at",
            "shift_plan_note",
            "shift_at",
            "shift_origin_berth",
            "shift_destination_berth",
            "shift_approval_status",
            "shift_approval_note",
            "shift_aborted_reason",
            "shift_decided_by",
            "shift_decided_at",
            "maneuver_history",
            "berth",
            "last_port",
            "next_port",
            "created_by",
            "notes",
            "created_at",
            "updated_at",
        ),
    },
    "conversations": {
        "pk": ("id",),
        "jsonb": set(),
        "columns": ("id", "username", "title", "created_at", "updated_at"),
    },
    "messages": {
        "pk": ("id",),
        "jsonb": {"citations", "channel_metadata"},
        "columns": (
            "id",
            "conversation_id",
            "role",
            "content",
            "citations",
            "feedback_status",
            "feedback_note",
            "feedback_correction",
            "feedback_correction_document",
            "feedback_error_type",
            "feedback_scope",
            "feedback_destination",
            "feedback_criticality",
            "feedback_updated_by",
            "feedback_updated_at",
            "channel",
            "channel_user_id",
            "external_message_id",
            "external_reply_to_id",
            "channel_metadata",
            "created_at",
        ),
    },
    "channel_events": {
        "pk": ("id",),
        "jsonb": {"payload"},
        "columns": (
            "id",
            "channel",
            "event_type",
            "username",
            "conversation_id",
            "local_message_id",
            "channel_user_id",
            "external_event_id",
            "external_message_id",
            "payload",
            "created_at",
        ),
    },
    "app_runtime_state": {
        "pk": ("key",),
        "jsonb": {"value"},
        "columns": ("key", "value", "updated_at"),
    },
    "feedback_eval_cases": {
        "pk": ("id",),
        "jsonb": {"expected_substrings"},
        "columns": (
            "id",
            "source_message_id",
            "document",
            "question",
            "expected_answer",
            "expected_substrings",
            "feedback_note",
            "updated_by",
            "source",
            "created_at",
            "updated_at",
        ),
    },
    "maneuver_cases": {
        "pk": ("maneuver_id",),
        "jsonb": {
            "vessel_snapshot",
            "scale_snapshot",
            "planning_snapshot",
            "decision_snapshot",
            "execution_snapshot",
            "outcome_snapshot",
            "environment_snapshot",
            "feature_snapshot",
            "change_log",
        },
        "columns": (
            "maneuver_id",
            "port_call_id",
            "reference_code",
            "vessel_name",
            "maneuver_type",
            "current_state",
            "origin_label",
            "destination_label",
            "planned_at",
            "decided_at",
            "completed_at",
            "reported_at",
            "latest_event_at",
            "case_summary",
            "vessel_snapshot",
            "scale_snapshot",
            "planning_snapshot",
            "decision_snapshot",
            "execution_snapshot",
            "outcome_snapshot",
            "environment_snapshot",
            "feature_snapshot",
            "change_log",
            "feedback_status",
            "feedback_note",
            "feedback_updated_by",
            "feedback_updated_at",
            "created_at",
            "updated_at",
        ),
    },
}
POSTGRES_INSERT_ORDER = (
    "app_users",
    "documents",
    "port_calls",
    "conversations",
    "messages",
    "channel_events",
    "app_runtime_state",
    "feedback_eval_cases",
    "maneuver_cases",
)
POSTGRES_DELETE_ORDER = (
    "channel_events",
    "messages",
    "conversations",
    "maneuver_cases",
    "port_calls",
    "feedback_eval_cases",
    "app_runtime_state",
    "documents",
    "app_users",
)
