"""Static admin QA case catalogues.

These lists are data, not runtime control flow. Keeping them outside the
suite runner makes the executable test code easier to review and maintain.
"""

BOT_CRITICAL_TEST_MATRIX: list[dict] = [
    {
        "id": "roro-north-strong",
        "group": "Rebocadores e vento",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Ro-Ro acima de 220 m com Norte forte",
        "question": "Quantos reboques para RORO de 230m a entrar com vento norte forte?",
        "expected_summary": "Recomenda 4 rebocadores grandes e preserva a excecao pratica acima de 220 m.",
        "source": "knowledge/tug_operational_guidance.json",
        "expected_origin": "operational_tug_guidance",
        "expected_tokens": ("Recomendo 4 rebocadores grandes", "mais de 220 m", "vento Norte forte"),
    },
    {
        "id": "autoeuropa-roro-live-weather-tugs",
        "group": "Rebocadores e vento",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Autoeuropa Ro-Ro com meteorologia atual",
        "question": "Tenho um navio para sair da Autoeuropa. É um roro com 200 m e tem bowthruster. Quantos reboques devo pedir face às condições meteorológicas atuais?",
        "expected_summary": "Cruza a regra de rebocadores com vento/rajadas atuais e não responde só com posicionamento.",
        "source": "knowledge/tug_operational_guidance.json + meteorologia live",
        "expected_origin": "operational_tug_guidance",
        "expected_tokens": (
            "Recomendo 2 rebocadores",
            "Ro-Ro com vento",
            "a sair: 2 rebocadores",
            "Meteorologia considerada",
            "Local: Autoeuropa",
        ),
    },
    {
        "id": "bulk-tms2-north-strong",
        "group": "Rebocadores e vento",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Graneleiro/contentores grande a sair com Norte forte",
        "question": "Um Graneleiro de 190m a sair do TMS2 com vento norte forte, quantos rebocadores leva?",
        "expected_summary": "Recomenda 4 grandes, mantendo a excecao Tanquisado/Eco-Oil/Lisnave caso a caso.",
        "source": "knowledge/tug_operational_guidance.json",
        "expected_origin": "operational_tug_guidance",
        "expected_tokens": ("Recomendo 4 rebocadores grandes", "vento Norte forte", "Tanquisado", "Eco-Oil"),
    },
    {
        "id": "lisnave-100-150",
        "group": "Rebocadores e vento",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Lacuna Lisnave 100-150 m",
        "question": "Um navio de 130m para a Lisnave precisa de quantos rebocadores?",
        "expected_summary": "Fecha a lacuna documental com regra pratica de 3 rebocadores.",
        "source": "knowledge/tug_operational_guidance.json",
        "expected_origin": "operational_tug_guidance",
        "expected_tokens": ("Recomendo 3 rebocadores", "acima de 100 m ate 150 m", "Quatro rebocadores sao excessivos"),
    },
    {
        "id": "diagnostic-lisnave-300-six-tugs",
        "group": "Diagnostico operacional",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "operational_diagnostic",
        "label": "Diagnostico Lisnave 300 m",
        "question": "Um navio na LISNAVE de 300 m manobra com quantos rebocadores normalmente?",
        "expected_summary": "A ficha deve aplicar o patamar especifico antes de qualquer minimo generico.",
        "source": "core/operational_diagnostics.py + knowledge/tug_operational_guidance.json",
        "expected_tokens": ("Minimo critico identificado: 6 rebocador", "Lisnave acima de 250 m: 6 rebocadores"),
    },
    {
        "id": "diagnostic-hidrolift-beam-limit",
        "group": "Diagnostico operacional",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "operational_diagnostic",
        "label": "Diagnostico Hidrolift boca 45 m",
        "question": "Tenho um navio para entrar no hidrolift no preia-mar das 20:03. O navio tem 45 m de boca, pode manobrar?",
        "expected_summary": "A ficha bloqueia pela boca antes de discutir a hora.",
        "source": "core/operational_diagnostics.py + IT-014",
        "expected_tokens": ("Bloqueio dimensional", "boca maxima 32 m", "Boca: 45 m"),
    },
    {
        "id": "diagnostic-ecooil-two-tugs",
        "group": "Diagnostico operacional",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "operational_diagnostic",
        "label": "Diagnostico Eco-Oil com 2 rebocadores",
        "question": "Entrada para Eco-Oil com 2 rebocadores pode avancar?",
        "expected_summary": "A ficha deve chamar o minimo pratico local de 3 rebocadores.",
        "source": "core/operational_diagnostics.py + knowledge/tug_operational_guidance.json",
        "expected_tokens": ("Eco-Oil: usar sempre no minimo 3 rebocadores", "Rebocadores insuficientes"),
    },
    {
        "id": "diagnostic-tanquisado-two-tugs",
        "group": "Diagnostico operacional",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "operational_diagnostic",
        "label": "Diagnostico Tanquisado com 2 rebocadores",
        "question": "Entrada para Tanquisado com 2 rebocadores pode avancar?",
        "expected_summary": "A ficha deve chamar o minimo pratico local de 3 rebocadores.",
        "source": "core/operational_diagnostics.py + knowledge/tug_operational_guidance.json",
        "expected_tokens": ("Tanquisado: usar sempre no minimo 3 rebocadores", "Rebocadores insuficientes"),
    },
    {
        "id": "diagnostic-route-reponto-lead-time",
        "group": "Diagnostico operacional",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "operational_diagnostic",
        "label": "Diagnostico percurso e reponto",
        "question": "Navio do Fundeadouro Norte para a Lisnave deve sair quando para chegar ao reponto das 20:03?",
        "expected_summary": "A ficha deve validar duracao origem-destino e hora de chegada ao ponto critico.",
        "source": "core/operational_diagnostics.py + knowledge/Notas_Pilotagem.txt",
        "expected_tokens": ("Percurso/duracao", "cerca de 1 hora e 30 minutos", "fase critica no cais/doca"),
    },
    {
        "id": "diagnostic-secil-reponto",
        "group": "Diagnostico operacional",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "operational_diagnostic",
        "label": "Diagnostico SECIL com reponto",
        "question": "Entrada para a SECIL W marcada para as 13:30, tenho de ir ao reponto?",
        "expected_summary": "A ficha deve tratar a SECIL como local critico de reponto e distinguir Oeste/Este.",
        "source": "core/operational_diagnostics.py + IT-009_Secil.txt",
        "expected_tokens": ("Local: SECIL", "SECIL W/Oeste", "todos os navios atracam proximo do reponto"),
    },
    {
        "id": "diagnostic-alstom-mandatory-rules",
        "group": "Diagnostico operacional",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "operational_diagnostic",
        "label": "Diagnostico ALSTOM regras obrigatorias",
        "question": "Entrada para a Alstom desde a Barra com vento 15 kts pode avançar?",
        "expected_summary": "A ficha deve aplicar estibordo, preia-mar, limite de vento, dia e uma manobra por reponto.",
        "source": "core/operational_diagnostics.py + IT-038_Alstom.txt",
        "expected_tokens": (
            "Local: ALSTOM",
            "atracam apenas por estibordo",
            "reponto de preia-mar",
            "1h30",
            "inferior a 15 kt",
            "atinge/excede o limite pratico",
        ),
    },
    {
        "id": "diagnostic-secil-isolates-old-lisnave-context",
        "group": "Diagnostico operacional",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "operational_diagnostic",
        "label": "Diagnostico SECIL sem herdar Lisnave",
        "question": "Marquei manobra de entrada para a Secil E as 1925. Está correto?",
        "history": [
            {
                "role": "user",
                "content": "Um navio na LISNAVE de 300 m manobra com quantos rebocadores normalmente?",
            },
            {"role": "assistant", "content": "Recomendo 6 rebocadores grandes."},
            {"role": "user", "content": "Com nevoeiro em porto posso avancar?"},
        ],
        "expected_summary": "A ficha deve tratar a SECIL E como novo caso e nao herdar Lisnave, nevoeiro ou rebocadores antigos.",
        "source": "core/chat_context_scope.py + core/operational_diagnostics.py",
        "expected_tokens": ("Local: SECIL", "Doca/cais: SECIL E/Este", "Hora referida: 19:25"),
        "forbidden_tokens": ("Local: LISNAVE", "6 rebocador", "nevoeiro"),
    },
    {
        "id": "conversation-context-sapec-non-imo-follow-up",
        "group": "Contexto conversacional",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "conversation_reasoning",
        "label": "Follow-up SAPEC carga não IMO",
        "question": "E carga não IMO",
        "history": [
            {
                "role": "user",
                "content": "Um navio com 9,2m de calado pode atracar na SAPEC Líquidos?",
            },
            {
                "role": "assistant",
                "content": "Depende se a carga é IMO ou não IMO e da altura de água.",
            },
            {"role": "user", "content": "E carga não IMO"},
        ],
        "expected_summary": "A ficha deve assumir continuidade SAPEC quando o follow-up curto não conflita.",
        "source": "core/chat_context_scope.py + core/chat_reasoning.py",
        "expected_tokens": (
            "Ficha de contexto provável",
            "Premissa de continuidade",
            "SAPEC / TPS-TGL",
            "Calado: 9,2 m.",
            "Carga: não IMO.",
        ),
    },
    {
        "id": "conversation-context-new-case-asks-confirmation",
        "group": "Contexto conversacional",
        "risk": "Alto",
        "mode": "Manual guiado",
        "runner": "manual",
        "label": "Mudança de caso sem herança indevida",
        "question": "Após falar da Lisnave, perguntar: Marquei entrada para Secil E às 19:25. Está correto?",
        "expected_summary": "Deve tratar Secil E como novo caso, sem herdar rebocadores, nevoeiro ou LOA da Lisnave.",
        "source": "core/chat_context_scope.py + /new",
        "expected_tokens": (),
    },
    {
        "id": "secil-e-entry-1925-reponto",
        "group": "SECIL e reponto",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Entrada Secil E 19:25 validada contra reponto",
        "question": "Marquei manobra de entrada para a Secil E as 1925. Está correta a hora?",
        "expected_summary": "A resposta deve validar a hora pelo reponto/antecedencia e nao apenas por inexistir proibicao noturna.",
        "source": "IT-009_Secil.txt + marés live quando disponíveis",
        "expected_origin": "secil_entry_timing",
        "expected_tokens": ("Secil E", "30-45 min", "não é apenas ser dia/noite"),
        "forbidden_tokens": ("não há proibição", "horário das 19:25 é, portanto, permitido"),
    },
    {
        "id": "alstom-barra-preia-mar-lead-time",
        "group": "Percursos e repontos",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "ALSTOM desde a Barra para preia-mar",
        "question": "Quanto tempo da Barra para o Cais Alstom para apanhar o reponto de preia-mar?",
        "expected_summary": "Usa a antecedencia operacional obrigatoria da ALSTOM, nao uma duracao generica do Canal Norte.",
        "source": "IT-038_Alstom.txt",
        "expected_origin": "operational_route_transit",
        "expected_tokens": ("Cais ALSTOM", "1 hora e 30 minutos antes da preia-mar", "reponto de preia-mar"),
    },
    {
        "id": "distance-tms1-alstom",
        "group": "Percursos e distancias",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Distancia TMS 1 - ALSTOM",
        "question": "Qual a distância do TMS 1 até à Alstom?",
        "expected_summary": "Usa a referencia direta de segmento TMS 1 -> ALSTOM.",
        "source": "knowledge/Notas_Pilotagem.txt",
        "expected_origin": "operational_route_transit",
        "expected_tokens": ("TMS 1", "Cais ALSTOM", "3,5 milhas náuticas", "pode ser somada"),
    },
    {
        "id": "distance-tms1-sapec",
        "group": "Percursos e distancias",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Distancia TMS 1 - SAPEC",
        "question": "Qual a distância do TMS 1 até à SAPEC?",
        "expected_summary": "Usa a referencia direta de segmento TMS 1 -> SAPEC.",
        "source": "knowledge/Notas_Pilotagem.txt",
        "expected_origin": "operational_route_transit",
        "expected_tokens": ("TMS 1", "SAPEC", "2,2 milhas náuticas", "pode ser somada"),
    },
    {
        "id": "distance-tms1-praias",
        "group": "Percursos e distancias",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Distancia TMS 1 - Praias do Sado",
        "question": "Qual a distância do TMS 1 até às Praias do Sado?",
        "expected_summary": "Usa a referencia direta de segmento TMS 1 -> Praias do Sado.",
        "source": "knowledge/Notas_Pilotagem.txt",
        "expected_origin": "operational_route_transit",
        "expected_tokens": ("TMS 1", "Praias do Sado", "1,6 milhas náuticas", "pode ser somada"),
    },
    {
        "id": "distance-tms1-autoeuropa",
        "group": "Percursos e distancias",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Distancia TMS 1 - Autoeuropa",
        "question": "Qual a distância do TMS 1 até à Autoeuropa em NM?",
        "expected_summary": "Aceita NM como unidade de distancia e usa a referencia direta.",
        "source": "knowledge/Notas_Pilotagem.txt",
        "expected_origin": "operational_route_transit",
        "expected_tokens": ("TMS 1", "Autoeuropa", "1,0 milha náutica", "pode ser somada"),
    },
    {
        "id": "distance-tms1-joao-farto",
        "group": "Percursos e distancias",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Distancia TMS 1 - Boia Joao Farto",
        "question": "Qual a distância do TMS 1 até à bóia João Farto?",
        "expected_summary": "Usa a referencia direta de segmento TMS 1 -> Boia Joao Farto.",
        "source": "knowledge/Notas_Pilotagem.txt",
        "expected_origin": "operational_route_transit",
        "expected_tokens": ("TMS 1", "Bóia João Farto", "1,6 milhas náuticas", "pode ser somada"),
    },
    {
        "id": "distance-tms1-outao",
        "group": "Percursos e distancias",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Distancia TMS 1 - Outao",
        "question": "Qual a distância do TMS 1 até ao Outão?",
        "expected_summary": "Usa a referencia direta de segmento TMS 1 -> Outao.",
        "source": "knowledge/Notas_Pilotagem.txt",
        "expected_origin": "operational_route_transit",
        "expected_tokens": ("TMS 1", "Outão", "3,0 milhas náuticas", "pode ser somada"),
    },
    {
        "id": "distance-tms1-fora-barra",
        "group": "Percursos e distancias",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Distancia TMS 1 - fora da Barra",
        "question": "Qual a distância do TMS 1 até fora da Barra?",
        "expected_summary": "Usa a referencia direta de segmento TMS 1 -> fora da Barra/Pilar 2.",
        "source": "knowledge/Notas_Pilotagem.txt",
        "expected_origin": "operational_route_transit",
        "expected_tokens": ("TMS 1", "fora da Barra", "6,0 milhas náuticas", "pode ser somada"),
    },
    {
        "id": "route-plan-joao-farto-alstom",
        "group": "Percursos e distancias",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Planeamento Canal Norte Joao Farto - ALSTOM",
        "question": "Estou na Bóia João Farto para a Alstom, quanto falta?",
        "expected_summary": "Calcula a distancia restante por pernadas e mostra rumos de entrada/saida.",
        "source": "knowledge/setubal_route_planning.json",
        "expected_origin": "operational_route_transit",
        "expected_tokens": ("Canal Norte", "5,0 milhas náuticas", "Bóia João Farto -> Bóia 1CC", "rumo 040°"),
        "forbidden_tokens": ("rumo inverso",),
    },
    {
        "id": "route-plan-full-north-channel",
        "group": "Percursos e distancias",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Canal Norte completo desde embarque",
        "question": "Da posição de embarque até ao fim do canal norte, qual a distância?",
        "expected_summary": "Soma todas as pernadas desde a pilot station ate ao fim do Canal Norte.",
        "source": "knowledge/setubal_route_planning.json",
        "expected_origin": "operational_route_transit",
        "expected_tokens": ("Pilot station", "Canal Norte", "10,3 milhas náuticas", "SAPEC -> Cais ALSTOM"),
    },
    {
        "id": "route-plan-tms2-north-channel-position",
        "group": "Percursos e distancias",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Referencia TMS2 no Canal Norte",
        "question": "Da entrada da barra ao TMS2 pelo canal norte, quanto falta?",
        "expected_summary": "Situa TMS1/TMS2 no Canal Norte antes da Autoeuropa, como referencia operacional.",
        "source": "knowledge/setubal_route_planning.json",
        "expected_origin": "operational_route_transit",
        "expected_tokens": ("Canal Norte", "6,5 milhas náuticas", "TMS 1 -> Bóia 5CC", "Bóia 5CC -> TMS 2"),
    },
    {
        "id": "route-plan-full-south-channel",
        "group": "Percursos e distancias",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Canal Sul ate Boia 14CS",
        "question": "Da entrada da barra até ao fim do canal sul, quais as milhas?",
        "expected_summary": "Soma o Canal Sul desde o Pilar 2 ate a Boia 14CS.",
        "source": "knowledge/setubal_route_planning.json",
        "expected_origin": "operational_route_transit",
        "expected_tokens": ("Pilar 2", "Bóia 14CS", "10,0 milhas náuticas", "Bóia 12CS -> Bóia 14CS"),
    },
    {
        "id": "route-plan-south-lisnave-eta",
        "group": "Percursos e distancias",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "ETA Boia 12CS - Lisnave",
        "question": "Da Bóia 12 CS para a Lisnave a 6 nós, saída às 10:00, qual ETA?",
        "expected_summary": "Calcula distancia, pernadas restantes e ETA com velocidade indicada.",
        "source": "knowledge/setubal_route_planning.json",
        "expected_origin": "operational_route_transit",
        "expected_tokens": ("Canal Sul para LISNAVE", "1,0 milha náutica", "A 6,0 kt", "ETA ao destino: 10:10"),
    },
    {
        "id": "route-plan-south-reverse-headings",
        "group": "Percursos e distancias",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Rumos inversos Lisnave - Pilar 2",
        "question": "Da Lisnave para o Pilar 2, quais os rumos de saída?",
        "expected_summary": "Aplica +180 graus aos rumos de entrada para sair no sentido inverso.",
        "source": "knowledge/setubal_route_planning.json",
        "expected_origin": "operational_route_transit",
        "expected_tokens": ("10,5 milhas náuticas", "rumo 210°", "rumo 245°", "rumo 220°"),
        "forbidden_tokens": ("rumo inverso",),
    },
    {
        "id": "route-plan-cross-channel-lisnave-tms1",
        "group": "Percursos e distancias",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Ligacao Lisnave - TMS1 via Joao Farto",
        "question": "Vou mudar um navio da LISNAVE para o TMS1. Se for a 5 kts quanto tempo levo de um cais ao outro?",
        "expected_summary": "Liga Canal Sul e Canal Norte pela Boia Joao Farto e calcula tempo a velocidade indicada.",
        "source": "knowledge/setubal_route_planning.json",
        "expected_origin": "operational_route_transit",
        "expected_tokens": (
            "Canal Sul / Canal Norte via Bóia João Farto",
            "7,9 milhas náuticas",
            "Bóia 4CS -> Bóia João Farto",
            "Bóia João Farto -> Bóia 1CC",
            "A 5,0 kt, duração estimada: 1 h 35 min.",
        ),
        "forbidden_tokens": ("rumo inverso",),
    },
    {
        "id": "tanquisado-east-side-push",
        "group": "Rebocadores e vento",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Tanquisado a sair com E forte",
        "question": "A sair de Tanquisado com vento E forte, onde meto o reboque?",
        "expected_summary": "Mantem proa+popa estabelecidos e aponta terceiro rebocador a empurrar ao costado na largada dos cabos.",
        "source": "knowledge/tug_operational_guidance.json",
        "expected_origin": "operational_tug_guidance",
        "expected_tokens": (
            "Tanquisado com 3 rebocadores",
            "1 a proa e 1 a popa",
            "terceiro",
            "Tanquisado a sair com vento E forte",
            "1 rebocador a empurrar ao costado",
            "largada dos cabos",
        ),
    },
    {
        "id": "ecooil-west-side-push",
        "group": "Rebocadores e vento",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Eco-Oil a sair com W forte",
        "question": "A sair da Eco-Oil com vento W forte, onde meto o reboque?",
        "expected_summary": "Mantem proa+popa estabelecidos e aponta terceiro rebocador a empurrar ao costado, como efeito oposto da Tanquisado.",
        "source": "knowledge/tug_operational_guidance.json",
        "expected_origin": "operational_tug_guidance",
        "expected_tokens": (
            "Eco-Oil com 3 rebocadores",
            "1 a proa e 1 a popa",
            "terceiro",
            "Eco-Oil a sair com vento W forte",
            "1 rebocador a empurrar ao costado",
            "oposto da Tanquisado",
        ),
    },
    {
        "id": "fourth-tug-side-push-or-standby",
        "group": "Rebocadores e vento",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "4.º rebocador: costado ou standby",
        "question": "Tenho 4 rebocadores na Tanquisado, onde meto o quarto reboque?",
        "expected_summary": "O quarto rebocador so empurra ao costado se houver espaco sem criar ma vizinhanca; senao fica standby.",
        "source": "knowledge/tug_operational_guidance.json",
        "expected_origin": "operational_tug_guidance",
        "expected_tokens": ("4.º rebocador", "empurrar ao costado", "ma vizinhanca", "standby"),
    },
    {
        "id": "five-tugs-lisnave-bow-south",
        "group": "Rebocadores e vento",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Lisnave 5 rebocadores proa a sul",
        "question": "Na Lisnave com 5 rebocadores e navio com proa a sul, onde meto os rebocadores?",
        "expected_summary": "Com proa a sul, ficam 2 a proa e 1 a popa estabelecidos.",
        "source": "knowledge/tug_operational_guidance.json",
        "expected_origin": "operational_tug_guidance",
        "expected_tokens": ("2 rebocadores a proa", "1 rebocador a popa", "standby"),
    },
    {
        "id": "five-tugs-lisnave-stern-south",
        "group": "Rebocadores e vento",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Lisnave 5 rebocadores popa a sul",
        "question": "Na Lisnave com 5 rebocadores e navio com popa a sul, onde meto os rebocadores?",
        "expected_summary": "Com popa a sul/proa a norte, ficam 2 a popa e 1 a proa estabelecidos.",
        "source": "knowledge/tug_operational_guidance.json",
        "expected_origin": "operational_tug_guidance",
        "expected_tokens": ("2 rebocadores a popa", "1 rebocador a proa", "standby"),
    },
    {
        "id": "six-tugs-positioning",
        "group": "Rebocadores e vento",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "6 rebocadores: 2+2 e dois ao costado",
        "question": "Com 6 rebocadores, onde meto os rebocadores?",
        "expected_summary": "Com 6, ficam 2 estabelecidos a proa e 2 a popa, mais 2 a empurrar ao costado.",
        "source": "knowledge/tug_operational_guidance.json",
        "expected_origin": "operational_tug_guidance",
        "expected_tokens": ("2 rebocadores a proa", "2 rebocadores a popa", "os outros 2 empurram ao costado"),
    },
    {
        "id": "small-deep-no-bowthruster",
        "group": "Rebocadores e vento",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Navio pequeno, fundo e sem bowthruster",
        "question": "Navio sem bowthruster de 110m e calado 8m precisa de quantos rebocadores?",
        "expected_summary": "Usa 1 rebocador grande de 35 t, nao rebocador pequeno.",
        "source": "knowledge/tug_operational_guidance.json",
        "expected_origin": "operational_tug_guidance",
        "expected_tokens": ("Recomendo 1 rebocador grande", "35 t", "nao rebocador pequeno"),
    },
    {
        "id": "fog-suspends-maneuver",
        "group": "Limites de seguranca",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Nevoeiro suspende a manobra",
        "question": "Um roro vai sair agora da Autoeuropa. Tem 200 m e ja pus 2 reboques. Pode sair? Ah, mas ficou nevoeiro!",
        "expected_summary": "Bloqueia a decisao: rebocadores nao compensam nevoeiro.",
        "source": "knowledge/operational_safety_limits.json",
        "expected_origin": "operational_safety_limit",
        "expected_tokens": ("Não.", "nevoeiro em porto", "manobras ficam suspensas", "rebocadores não elimina"),
    },
    {
        "id": "fog-underway-colreg-procedure",
        "group": "Limites de seguranca",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Nevoeiro súbito em navegação: COLREG",
        "question": "Se um navio for apanhado no meio do nevoeiro a navegar, que procedimentos deve adoptar segundo a COLREG?",
        "expected_summary": "Nao bloqueia apenas com suspensao: aplica RIEAM/COLREG, sinais de nevoeiro e decisao local cais/fundeadouro/abortar.",
        "source": "knowledge/operational_safety_limits.json + knowledge/RIEAM_COLREG_Regras_Estrada.txt",
        "expected_origin": "fog_underway_procedure",
        "expected_tokens": (
            "Regra 19",
            "Regra 35",
            "1 som prolongado",
            "avaliar posição",
            "cais de destino",
            "fundeadouro",
            "abortar antes de entrar",
            "VHF 73",
        ),
    },
    {
        "id": "wind-31-suspends-maneuver",
        "group": "Limites de seguranca",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "31 kt suspende mesmo com mais rebocadores",
        "question": "Se estiver 31 kts de vento, posso sair com 4 rebocadores?",
        "expected_summary": "Suspende acima de 25 kt e so admite retoma abaixo de 25 kt.",
        "source": "knowledge/operational_safety_limits.json",
        "expected_origin": "operational_safety_limit",
        "expected_tokens": ("31 kt", "manobras ficam suspensas", "mais rebocadores não anula", "menos de 25 kt"),
    },
    {
        "id": "colreg-narrow-channel-overtaking",
        "group": "RIEAM/COLREG",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "COLREG ultrapassagem canal estreito",
        "question": "Pelo COLREG, quero ultrapassar num canal estreito. Que sinais uso?",
        "expected_summary": "Interpreta Regra 9 e Regra 34 com sinais de ultrapassagem e acordo.",
        "source": "knowledge/RIEAM_COLREG_Regras_Estrada.txt",
        "expected_origin": "colreg_interpretation",
        "expected_tokens": ("Regra 9", "Regra 34", "2 sons prolongados + 1 curto", "5 sons curtos"),
    },
    {
        "id": "colreg-dredging-safe-side",
        "group": "RIEAM/COLREG",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "COLREG dragagem bordo livre",
        "question": "No RIEAM, uma draga com vermelho vermelho e verde verde indica o quê?",
        "expected_summary": "Interpreta Regra 27: vermelho marca obstrucao e verde marca bordo livre.",
        "source": "knowledge/RIEAM_COLREG_Regras_Estrada.txt",
        "expected_origin": "colreg_interpretation",
        "expected_tokens": ("Regra 27", "bordo obstruído", "bordo por onde se pode passar"),
    },
    {
        "id": "visibility-one-km-threshold",
        "group": "Limites de seguranca",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "knowledge_json",
        "label": "Limiar live de visibilidade",
        "question": "Se o live feed indicar 1,0 km de visibilidade, o bot trata como visibilidade reduzida?",
        "expected_summary": "O limiar tecnico fica fixado em 1,0 km para interpretar dados live.",
        "source": "knowledge/operational_safety_limits.json",
        "source_path": "operational_safety_limits.json",
        "expected_tokens": ("fog_visibility_km_reference", "1.0", "visibilidade operacional"),
    },
    {
        "id": "loss-of-engine-emergency",
        "group": "Limites de seguranca",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Perda de maquina: ferro e VTS",
        "question": "O navio ficou sem maquina e ainda nao tem rebocadores perto. O que aconselhas de imediato?",
        "expected_summary": "Prioriza largar ferro, VTS no canal 73 e nao cai na resposta de posicionamento de rebocadores.",
        "source": "knowledge/operational_safety_limits.json",
        "expected_origin": "operational_emergency_response",
        "expected_tokens": ("largar ferro imediatamente", "VHF 73", "canal 14", "canal 71"),
    },
    {
        "id": "loss-of-bow-emergency",
        "group": "Limites de seguranca",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Emergencia: perda de bow",
        "question": "Se o navio perder bow na manobra, o que faz?",
        "expected_summary": "A resposta manda largar ferro com 1 manilha na agua e reportar nos canais certos.",
        "source": "knowledge/operational_safety_limits.json",
        "expected_origin": "operational_emergency_response",
        "expected_tokens": ("1 manilha na agua", "VHF 73", "canal 14"),
    },
    {
        "id": "parted-lines-emergency",
        "group": "Limites de seguranca",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Emergencia: cabos partidos",
        "question": "Se partirem cabos na manobra, qual e a resposta imediata?",
        "expected_summary": "A resposta prepara ferro, novos cabos, lancha de cabos e rebocadores de atencao.",
        "source": "knowledge/operational_safety_limits.json",
        "expected_origin": "operational_emergency_response",
        "expected_tokens": ("preparar novos cabos", "lancha de cabos", "rebocadores de atencao"),
    },
    {
        "id": "parted-tug-line-emergency",
        "group": "Limites de seguranca",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Emergencia: cabo do reboque",
        "question": "Se o cabo do reboque partir, o que fazemos?",
        "expected_summary": "A resposta manda preparar cabo de amarracao do navio, solto e sem guincho, para o reboque.",
        "source": "knowledge/operational_safety_limits.json",
        "expected_origin": "operational_emergency_response",
        "expected_tokens": ("cabo de amarracao do navio", "sem estar no guincho", "fazer firme ao reboque"),
    },
    {
        "id": "grounding-emergency",
        "group": "Limites de seguranca",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Emergencia: encalhe",
        "question": "Se encalhar, qual e a resposta imediata?",
        "expected_summary": "A resposta manda ver profundidades, avaliar a mare, chamar rebocadores e considerar ferro.",
        "source": "knowledge/operational_safety_limits.json",
        "expected_origin": "operational_emergency_response",
        "expected_tokens": ("verificar profundidades", "avaliar a situacao com a mare", "chamar rebocadores"),
    },
    {
        "id": "collision-emergency",
        "group": "Limites de seguranca",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Emergencia: colisao",
        "question": "Se colidir na manobra, qual e a resposta imediata?",
        "expected_summary": "A resposta manda largar ferro imediatamente, chamar rebocadores e esquivar/afastar.",
        "source": "knowledge/operational_safety_limits.json",
        "expected_origin": "operational_emergency_response",
        "expected_tokens": ("largar ferro imediatamente", "chamar rebocadores", "esquivar-se"),
    },
    {
        "id": "shiphandling-practical-source",
        "group": "Fontes de conhecimento",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "knowledge_text",
        "label": "Notes on Shiphandling incorporado",
        "question": "A fonte de shiphandling cobre pivot point, reboques, bow thruster e ferro?",
        "expected_summary": "Garante que a sintese operacional extraida do PDF esta presente no conhecimento indexavel.",
        "source": "knowledge/Notes_on_Shiphandling_Practical.txt",
        "source_path": "Notes_on_Shiphandling_Practical.txt",
        "expected_tokens": ("pivot point", "1 a proa + 1 a popa", "Bow thruster", "largar ferro", "VHF 73"),
    },
    {
        "id": "navigation-lights-source",
        "group": "Fontes de conhecimento",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "knowledge_text",
        "label": "Lista de Luzes Setubal incorporada",
        "question": "A fonte de balizagem/luzes de Setubal esta indexavel no conhecimento?",
        "expected_summary": "Garante que a lista de luzes contem IALA A, 1CN, 2CS e Doca Pesca.",
        "source": "knowledge/Lista_Luzes_Setubal.txt",
        "source_path": "Lista_Luzes_Setubal.txt",
        "expected_tokens": ("SISTEMA IALA", "IALA A", "Boia N.º 1CN", "Fl G 3s", "Boia N.º 2CS", "Doca Pesca"),
    },
    {
        "id": "navigation-light-1cn-direct",
        "group": "Fontes de conhecimento",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Caracteristica da Boia 1CN",
        "question": "Qual e a caracteristica da Boia 1CN?",
        "expected_summary": "Responde pela tabela estruturada de luzes e inclui IALA A.",
        "source": "knowledge/navigation_lights_setubal.json",
        "expected_origin": "navigation_lights",
        "expected_tokens": ("Boia N.º 1CN", "Fl G 3s", "38º30,33'N", "8º51,46'W", "IALA A"),
    },
    {
        "id": "navigation-lights-iala-direct",
        "group": "Fontes de conhecimento",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Setubal usa IALA A",
        "question": "Em Setubal usamos que sistema IALA?",
        "expected_summary": "Confirma explicitamente IALA A e a leitura bombordo/estibordo.",
        "source": "knowledge/navigation_lights_setubal.json",
        "expected_origin": "navigation_lights",
        "expected_tokens": ("IALA A", "bombordo", "vermelhas", "estibordo", "verdes"),
    },
    {
        "id": "setubal-history-culture-source",
        "group": "Fontes de conhecimento",
        "risk": "Medio",
        "mode": "Automatico",
        "runner": "knowledge_text",
        "label": "Historia e cultura de Setubal",
        "question": "Existe contexto historico/cultural de Setubal sem misturar com regras tecnicas?",
        "expected_summary": "Garante contexto sobre Cetobriga, Forte de Sao Filipe, Outao e choco frito, com nota de nao uso operacional.",
        "source": "knowledge/Setubal_Historia_Cultura.txt",
        "source_path": "Setubal_Historia_Cultura.txt",
        "expected_tokens": (
            "Cetobriga",
            "Forte de Sao Filipe",
            "Outao",
            "choco frito",
            "Nao deve ser usado para validar manobras",
        ),
    },
    {
        "id": "rieam-colreg-road-rules-source",
        "group": "Fontes de conhecimento",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "knowledge_text",
        "label": "RIEAM/COLREG regras da estrada",
        "question": "A fonte RIEAM/COLREG cobre as regras centrais de anti colisao?",
        "expected_summary": "Garante vigia, velocidade segura, risco, roda a roda, rumos cruzados, canais e visibilidade reduzida.",
        "source": "knowledge/RIEAM_COLREG_Regras_Estrada.txt",
        "source_path": "RIEAM_COLREG_Regras_Estrada.txt",
        "expected_tokens": (
            "Regra 5 - Vigia",
            "Regra 7 - Risco de abalroamento",
            "Regra 14 - Roda a roda",
            "guinar para estibordo",
            "Regra 15 - Rumos cruzados",
            "ve o outro por estibordo",
            "Regra 19",
            "visibilidade reduzida",
            "Regra 34 - Ultrapassagem em canal estreito",
            "Regra 27 - Dragagem/trabalhos submarinos",
            "Anexo IV - Perigo",
        ),
    },
    {
        "id": "navigation-basics-source",
        "group": "Noções básicas de navegação",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "knowledge_text",
        "label": "Unidades náuticas e Beaufort incorporadas",
        "question": "A fonte de unidades e Beaufort cobre as conversões essenciais?",
        "expected_summary": "Garante milha náutica, nó, jarda, manilha e escala Beaufort.",
        "source": "knowledge/Nocoes_Basicas_Navegacao_Unidades.txt",
        "source_path": "Nocoes_Basicas_Navegacao_Unidades.txt",
        "expected_tokens": (
            "1 milha nautica = 1852 m",
            "1 no = 1 milha nautica por hora",
            "1 jarda = 0,9144 m",
            "1 manilha = 27,5 m",
            "Beaufort 6: 22-27 kt",
        ),
    },
    {
        "id": "navigation-units-km-to-nautical-miles",
        "group": "Noções básicas de navegação",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Conversão km para milhas náuticas",
        "question": "20 km são quantas milhas náuticas?",
        "expected_summary": "Converte km para milhas náuticas sem depender de interpretação textual.",
        "source": "knowledge/Nocoes_Basicas_Navegacao_Unidades.txt",
        "expected_origin": "navigation_basics",
        "expected_tokens": ("20 km", "10,80 milhas náuticas", "1 milha náutica = 1852 m"),
    },
    {
        "id": "navigation-units-shackle-to-meters",
        "group": "Noções básicas de navegação",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Manilha para metros",
        "question": "1 manilha são quantos metros?",
        "expected_summary": "Fixa a equivalência operacional da manilha.",
        "source": "knowledge/Nocoes_Basicas_Navegacao_Unidades.txt",
        "expected_origin": "navigation_basics",
        "expected_tokens": ("1 manilha", "27,5 metros", "1 manilha = 27,5 m"),
    },
    {
        "id": "navigation-units-yards-to-meters",
        "group": "Noções básicas de navegação",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Jardas para metros",
        "question": "100 jardas são quantos metros?",
        "expected_summary": "Converte jardas para metros.",
        "source": "knowledge/Nocoes_Basicas_Navegacao_Unidades.txt",
        "expected_origin": "navigation_basics",
        "expected_tokens": ("100 jardas", "91,44 metros", "1 jarda = 0,9144 m"),
    },
    {
        "id": "navigation-beaufort-force-six",
        "group": "Noções básicas de navegação",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Beaufort força 6",
        "question": "Força 6 Beaufort equivale a quantos nós?",
        "expected_summary": "Reconhece Beaufort e devolve kt/kmh.",
        "source": "knowledge/Nocoes_Basicas_Navegacao_Unidades.txt",
        "expected_origin": "navigation_basics",
        "expected_tokens": ("Beaufort 6", "22-27 kt", "39-49 km/h", "vento fresco"),
    },
    {
        "id": "ecooil-profile",
        "group": "Cais criticos",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "berth_profile",
        "label": "Perfil Eco-Oil",
        "question": "Que regras tenho para a Eco-Oil?",
        "expected_summary": "Calado, reponto, noite e defensas aparecem a partir do IT-008.",
        "source": "knowledge/berth_profiles.json",
        "profile_query": "Eco-Oil",
        "expected_tokens": ("IT-008_EcoOil.txt", "Calado maximo", "repontos de mare", "Atracacao noturna proibida"),
    },
    {
        "id": "tanquisado-profile",
        "group": "Cais criticos",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "berth_profile",
        "label": "Perfil Tanquisado",
        "question": "Quais os limites da Tanquisado?",
        "expected_summary": "Calado, reponto, noite e regra de saida fora de reponto aparecem a partir do IT-010.",
        "source": "knowledge/berth_profiles.json",
        "profile_query": "Tanquisado",
        "expected_tokens": ("IT-010_Tanquisado.txt", "Calado diurno praticavel", "repontos de mare", "Saida fora de reponto"),
    },
    {
        "id": "lisnave-profile",
        "group": "Cais criticos",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "berth_profile",
        "label": "Perfil Lisnave",
        "question": "Que regras ha na Lisnave para docas e cais?",
        "expected_summary": "Reponto, LOA noturna, calado variavel e orientacao operacional saem do IT-014.",
        "source": "knowledge/berth_profiles.json",
        "profile_query": "Lisnave",
        "expected_tokens": ("IT-014_Lisnave.txt", "repontos de mare", "280 m", "Calado"),
    },
    {
        "id": "lisnave-dock-checklist",
        "group": "Checklist de manobras",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "maneuver_checklist",
        "label": "Doca Lisnave com 3 rebocadores",
        "question": "A checklist da manobra avisa se uma doca Lisnave estiver com 3 rebocadores?",
        "expected_summary": "A checklist marca cautela, minimo de 4 rebocadores e proa a norte.",
        "source": "Pagina da manobra + domain/lisnave_rules.py",
        "fixture": "lisnave_dock_three_tugs",
        "expected_tokens": ("Lisnave - doca", "pelo menos 4 rebocadores", "proa a norte"),
    },
    {
        "id": "lisnave-d31-bow-south-checklist",
        "group": "Checklist de manobras",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "maneuver_checklist",
        "label": "D31/D32/D33 Lisnave com proa a sul",
        "question": "A checklist distingue D31/D32/D33 das docas 20/21/22 na orientação?",
        "expected_summary": "D31/D32/D33 entram via Hidrolift e ficam com proa a sul, apesar de serem docas Lisnave.",
        "source": "Pagina da manobra + domain/lisnave_rules.py",
        "fixture": "lisnave_dock31_four_tugs",
        "expected_tokens": ("D31, D32 e D33", "Hidrolift", "proa a sul"),
    },
    {
        "id": "lisnave-quay-checklist",
        "group": "Checklist de manobras",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "maneuver_checklist",
        "label": "Cais Lisnave com orientacao certa",
        "question": "A checklist distingue cais Lisnave de doca seca?",
        "expected_summary": "A checklist mostra proa a sul e nao aplica minimo de doca seca ao cais.",
        "source": "Pagina da manobra + domain/lisnave_rules.py",
        "fixture": "lisnave_quay_three_tugs",
        "expected_tokens": ("Orientação Lisnave", "proa a sul", "não se aplica às docas"),
    },
    {
        "id": "ecooil-checklist",
        "group": "Checklist de manobras",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "maneuver_checklist",
        "label": "Eco-Oil na checklist",
        "question": "A checklist puxa regras Eco-Oil para uma entrada?",
        "expected_summary": "A checklist inclui IT-008, calados, reponto e proibicao noturna de atracacao.",
        "source": "Pagina da manobra + knowledge/berth_profiles.json",
        "fixture": "ecooil_entry",
        "expected_tokens": ("IT-008_EcoOil.txt", "Calado maximo", "repontos de mare", "Atracacao noturna proibida"),
    },
    {
        "id": "tanquisado-checklist",
        "group": "Checklist de manobras",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "maneuver_checklist",
        "label": "Tanquisado na checklist",
        "question": "A checklist puxa regras Tanquisado para uma saida?",
        "expected_summary": "A checklist inclui IT-010, calado maximo e regra de saida fora de reponto.",
        "source": "Pagina da manobra + knowledge/berth_profiles.json",
        "fixture": "tanquisado_departure",
        "expected_tokens": ("IT-010_Tanquisado.txt", "calado maximo absoluto", "Saida fora de reponto", "preia-mar precedente"),
    },
    {
        "id": "validar-manobra-tanquisado-entry",
        "group": "Comandos slash",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "slash_validation",
        "label": "/validar-manobra Tanquisado com 2 rebocadores",
        "question": "/validar-manobra para entrada GALBOT em Tanquisado com só 2 rebocadores",
        "expected_summary": "A resposta deve priorizar IT-010/checklist, apanhar o novo mínimo prático de 3 rebocadores e não depender do histórico.",
        "source": "Comando /validar-manobra + knowledge/berth_profiles.json",
        "fixture": "tanquisado_entry_validation",
        "expected_tokens": (
            "Base documental acionada: IT-010_Tanquisado.txt",
            "Parecer operacional",
            "Decisão: NÃO AVANÇAR",
            "A marcação acerta a janela de reponto",
            "mínimo prático para Tanquisado",
            "Recomendação operacional",
            "histórico não usado como regra principal",
            "Janela planeada",
        ),
    },
    {
        "id": "validar-manobra-tanquisado-fora-reponto",
        "group": "Comandos slash",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "slash_validation",
        "label": "/validar-manobra Tanquisado fora do reponto",
        "question": "/validar-manobra para entrada Tanquisado marcada cedo demais para a maré",
        "expected_summary": "A resposta deve bloquear a validação quando a chegada estimada falha o reponto.",
        "source": "Comando /validar-manobra + tabela de marés + IT-010",
        "fixture": "tanquisado_entry_bad_tide",
        "expected_tokens": (
            "Decisão: NÃO AVANÇAR",
            "A marcação não cai suficientemente em cima do reponto",
            "Janela vencida com pontos pendentes",
            "IT-010_Tanquisado.txt",
        ),
    },
    {
        "id": "validar-manobra-ecooil-entry",
        "group": "Comandos slash",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "slash_validation",
        "label": "/validar-manobra Eco-Oil",
        "question": "/validar-manobra para entrada Eco-Oil marcada para chegar ao reponto",
        "expected_summary": "A resposta deve aplicar IT-008, reponto e leitura de calado/LOA sem depender do histórico; a decisão final pode endurecer com meteo/ondulação live.",
        "source": "Comando /validar-manobra + knowledge/berth_profiles.json",
        "fixture": "ecooil_entry_validation",
        "expected_tokens": (
            "Base documental acionada: IT-008_EcoOil.txt",
            "A marcação acerta a janela de reponto",
            "Calado (atracação)",
        ),
    },
    {
        "id": "validar-manobra-lisnave-doca-rebocadores",
        "group": "Comandos slash",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "slash_validation",
        "label": "/validar-manobra doca Lisnave",
        "question": "/validar-manobra para entrada de doca Lisnave com só 3 rebocadores",
        "expected_summary": "A resposta deve apanhar a regra prática de doca Lisnave e impedir parecer favorável.",
        "source": "Comando /validar-manobra + domain/lisnave_rules.py + IT-014",
        "fixture": "lisnave_dock_three_tugs_validation",
        "expected_tokens": (
            "Decisão: NÃO AVANÇAR",
            "Lisnave - doca",
            "pelo menos 4 rebocadores",
            "IT-014_Lisnave.txt",
        ),
    },
    {
        "id": "validar-manobra-mudanca-duas-fases",
        "group": "Comandos slash",
        "risk": "Alto",
        "mode": "Automatico",
        "runner": "slash_validation",
        "label": "/validar-manobra mudança",
        "question": "/validar-manobra para mudança Lisnave -> TMS 1 - Cais 4",
        "expected_summary": "A resposta deve tratar mudança como largada da origem e atracação no destino.",
        "source": "Comando /validar-manobra + perfis de cais origem/destino",
        "fixture": "shift_lisnave_to_tms1_validation",
        "expected_tokens": (
            "Mudança: validar o mesmo plano como largada da origem e atracação no destino",
            "LOA (largada da origem)",
            "LOA (atracação no destino)",
            "Regras do cais de origem",
            "Regras do cais de destino",
        ),
    },
    {
        "id": "repontos-canal-sul-origens-criticas",
        "group": "Repontos, Marés e Prioridades",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "knowledge_text",
        "label": "Lisnave, Tanquisado e Eco-Oil por origem",
        "question": "Quanto tempo antes marco entradas para Lisnave, Tanquisado ou Eco-Oil desde Barra, Fundeadouro Norte e Tróia?",
        "expected_summary": "Fixa 2h Barra, 1h30 Fundeadouro Norte e 1h Tróia para chegar ao reponto.",
        "source": "knowledge/Marcar_manobra_repontos_mare.txt",
        "source_path": "Marcar_manobra_repontos_mare.txt",
        "expected_tokens": (
            "De fora da Barra para Lisnave / Tanquisado / Eco-Oil:",
            "marcar 2h00 antes do reponto",
            "Do Fundeadouro Norte para Lisnave / Tanquisado / Eco-Oil:",
            "marcar 1h30 antes do reponto",
            "Do Fundeadouro de Tróia para Lisnave / Tanquisado / Eco-Oil:",
            "marcar 1h00 antes do reponto",
        ),
    },
    {
        "id": "repontos-teporset-termitrena-entrada-saida",
        "group": "Repontos, Marés e Prioridades",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "knowledge_text",
        "label": "Teporset/Termitrena entrada e saída",
        "question": "Como marco Teporset/Termitrena com calado condicionante e como marco a saída?",
        "expected_summary": "Entrada por origem para reponto/preia-mar e saída 15 min antes do reponto.",
        "source": "knowledge/Marcar_manobra_repontos_mare.txt",
        "source_path": "Marcar_manobra_repontos_mare.txt",
        "expected_tokens": (
            "Teporset / Termitrena com calado condicionante:",
            "Entrada: 2h00 de fora da Barra, 1h30 do Fundeadouro Norte, 1h00 do",
            "Saída: marcar 15 min antes do reponto",
            "reponto local ocorre",
        ),
    },
    {
        "id": "repontos-lisnave-docas-saida",
        "group": "Repontos, Marés e Prioridades",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "knowledge_text",
        "label": "Lisnave Docas 21/22 saída",
        "question": "Quando marco uma saída das Docas 21/22 da Lisnave?",
        "expected_summary": "Docas secas 21/22 saem 2h antes da preia-mar.",
        "source": "knowledge/Marcar_manobra_repontos_mare.txt",
        "source_path": "Marcar_manobra_repontos_mare.txt",
        "expected_tokens": (
            "Saída das Docas 21 ou 22",
            "Marcar 2h00 antes da preia-mar",
            "docas secas do Estaleiro Lisnave",
        ),
    },
    {
        "id": "repontos-tanquisado-ecooil-lisnave-mudanca",
        "group": "Repontos, Marés e Prioridades",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "knowledge_text",
        "label": "Tanquisado/Eco-Oil para Lisnave",
        "question": "Quando marco mudança de Tanquisado/Eco-Oil para Lisnave, incluindo Doca 21?",
        "expected_summary": "Regra normal 1h antes do reponto; Doca 21/22 grande pode exigir 2h antes da preia-mar.",
        "source": "knowledge/Marcar_manobra_repontos_mare.txt",
        "source_path": "Marcar_manobra_repontos_mare.txt",
        "expected_tokens": (
            "SECÇÃO 3 — MUDANÇA TANQUISADO OU ECO-OIL PARA LISNAVE",
            "Antecedência de marcação normal: 1 hora antes do reponto",
            "Doca 21 ou Doca 22",
            "2 horas antes da preia-mar",
        ),
    },
    {
        "id": "repontos-secil-entrada-saida-origem",
        "group": "Repontos, Marés e Prioridades",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "knowledge_text",
        "label": "SECIL W/E entrada e saída",
        "question": "Como marco entrada e saída da SECIL por origem?",
        "expected_summary": "Entradas 30-45 min ou 45-60 min antes do reponto; saídas 15 min antes.",
        "source": "knowledge/Marcar_manobra_repontos_mare.txt",
        "source_path": "Marcar_manobra_repontos_mare.txt",
        "expected_tokens": (
            "ENTRADAS PARA A SECIL:",
            "De fora da Barra: normalmente marcar 30 a 45 minutos antes do reponto",
            "Do Fundeadouro de Tróia ou de outro cais: marcar 45 minutos a 1 hora antes",
            "SAÍDAS DA SECIL:",
            "Marcar cerca de 15 minutos antes do reponto",
            "Usam-se tanto repontos de preia-mar como de baixa-mar",
        ),
    },
    {
        "id": "repontos-tms-high-draft-entry-departure",
        "group": "Repontos, Marés e Prioridades",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "knowledge_text",
        "label": "TMS1/TMS2 grande calado",
        "question": "Como marco TMS 1/TMS 2 com calados 9, 10,5 e 12 m?",
        "expected_summary": "Entrada 1h-1h30 antes da preia-mar; saída 30 min antes do reponto.",
        "source": "knowledge/Marcar_manobra_repontos_mare.txt",
        "source_path": "Marcar_manobra_repontos_mare.txt",
        "expected_tokens": (
            "CONDIÇÃO: Navios com calado entre 9 metros e 12 metros",
            "Entrada: marcar entre 1 hora e 1 hora e 30 minutos antes da preia-mar",
            "Saída: para navios de grande calado, marcar 30 minutos antes do reponto",
        ),
    },
    {
        "id": "repontos-sapec-tps-tgl-high-draft",
        "group": "Repontos, Marés e Prioridades",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "knowledge_text",
        "label": "SAPEC TPS/TGL calado e IMO",
        "question": "Como marco SAPEC Sólidos e Líquidos com calado alto, IMO e não-IMO?",
        "expected_summary": "TPS/TGL com preia-mar, saída 30 min antes do reponto, e TGL distingue 9,5 m IMO / 10,0 m não-IMO.",
        "source": "knowledge/Marcar_manobra_repontos_mare.txt",
        "source_path": "Marcar_manobra_repontos_mare.txt",
        "expected_tokens": (
            "Entrada TPS: marcar 1 hora e 30 minutos antes da preia-mar",
            "Saída TPS com grande calado: marcar 30 minutos antes do reponto",
            "Carga IMO: calado máximo de referência 9,5 m",
            "Carga não-IMO: calado máximo de referência 10,0 m",
            "fórmula de calado praticável",
        ),
    },
    {
        "id": "repontos-priority-order",
        "group": "Repontos, Marés e Prioridades",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "knowledge_text",
        "label": "Prioridade de navios e manobras",
        "question": "Que prioridade dou se várias manobras competirem pela mesma janela?",
        "expected_summary": "Janelas críticas primeiro; depois passageiros/animais/reefers/perecível, Ro-Ro, contentores, outros; saídas > mudanças > entradas.",
        "source": "knowledge/Condicoes_Meteorologicas_Prioridades.txt",
        "source_path": "Condicoes_Meteorologicas_Prioridades.txt",
        "expected_tokens": (
            "1.ª PRIORIDADE — NAVIOS QUE PRECISAM DE REPONTO OU JANELA CRÍTICA DE MARÉ",
            "passageiros/animais vivos/reefers/carga perecível",
            "saídas > mudanças > entradas",
        ),
    },
    {
        "id": "same-berth-priority-p13",
        "group": "Repontos, Marés e Prioridades",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Prioridade mesmo cais P-13",
        "question": "Quando dois navios pretendem o mesmo cais, qual tem prioridade?",
        "expected_summary": "Disputa pelo mesmo cais deve usar P-13/8 NM antes da prioridade geral de planeamento.",
        "source": "P-13_PlaneamentoGestao.txt",
        "expected_origin": "operational_priority",
        "expected_tokens": ("8 milhas náuticas", "Baliza número 2", "planeamento geral"),
    },
    {
        "id": "repontos-direct-barra-lisnave-2003",
        "group": "Repontos, Marés e Prioridades",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Barra -> Lisnave para reponto",
        "question": "Navio da Barra para Lisnave deve sair quando para chegar ao reponto das 20:03?",
        "expected_summary": "Pergunta natural deve aplicar 2h desde a Barra para cais do Canal Sul.",
        "source": "Marcar_manobra_repontos_mare.txt + berth_profiles.json",
        "expected_origin": "operational_tide_scheduling",
        "expected_tokens": ("fora da Barra", "2 horas antes do reponto", "20:03", "18:03", "LISNAVE"),
    },
    {
        "id": "repontos-direct-troia-ecooil-2003",
        "group": "Repontos, Marés e Prioridades",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Tróia -> Eco-Oil para reponto",
        "question": "Navio de Troia para Eco-Oil deve sair quando para chegar ao reponto das 20:03?",
        "expected_summary": "Pergunta natural deve aplicar 1h desde Tróia/Fundeadouro Sul.",
        "source": "Marcar_manobra_repontos_mare.txt + berth_profiles.json",
        "expected_origin": "operational_tide_scheduling",
        "expected_tokens": ("Tróia/Fundeadouro Sul", "1 hora antes do reponto", "20:03", "19:03", "Eco-Oil"),
    },
    {
        "id": "repontos-direct-tms-high-draft-entry",
        "group": "Repontos, Marés e Prioridades",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "TMS com grande calado",
        "question": "Um navio com 10,5 m de calado quer entrar no TMS 1 à preia-mar das 14:00. Quando marco?",
        "expected_summary": "Entrada TMS1/TMS2 com grande calado deve devolver janela 1h-1h30 antes da preia-mar.",
        "source": "core/operational_sources.py + Marcar_manobra_repontos_mare.txt",
        "expected_origin": "operational_tide_scheduling",
        "expected_tokens": ("TMS 1/TMS 2", "1h a 1h30 antes da preia-mar", "12:30-13:00", "calado praticável"),
    },
    {
        "id": "repontos-direct-tms-plural-calados",
        "group": "Repontos, Marés e Prioridades",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "TMS plural calados",
        "question": "Como marco TMS 1/TMS 2 com calados 9, 10,5 e 12 m?",
        "expected_summary": "Pergunta plural sobre calados deve acionar a regra de maré, não o perfil de cais.",
        "source": "core/operational_sources.py + Marcar_manobra_repontos_mare.txt",
        "expected_origin": "operational_tide_scheduling",
        "expected_tokens": ("calado entre 9 m e 12 m", "1h a 1h30 antes da preia-mar", "calado praticável"),
    },
    {
        "id": "repontos-direct-sapec-high-draft-departure",
        "group": "Repontos, Marés e Prioridades",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "SAPEC saída grande calado",
        "question": "Um navio de grande calado quer sair da SAPEC ao reponto das 14:00. Quando marco?",
        "expected_summary": "Saída SAPEC grande calado deve marcar 30 min antes do reponto.",
        "source": "core/operational_sources.py + IT-029_SAPEC.txt",
        "expected_origin": "operational_tide_scheduling",
        "expected_tokens": ("SAPEC", "30 min antes do reponto", "13:30"),
    },
    {
        "id": "repontos-direct-sapec-tgl-imo-entry",
        "group": "Repontos, Marés e Prioridades",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "SAPEC Líquidos IMO",
        "question": "SAPEC Líquidos com 9,4 m de calado e carga IMO deve entrar à preia-mar das 14:00, quando marco?",
        "expected_summary": "TGL deve responder com 1h30 antes, limite IMO/não-IMO e fórmula de calado praticável.",
        "source": "core/operational_sources.py + IT-029_SAPEC.txt",
        "expected_origin": "operational_tide_scheduling",
        "expected_tokens": ("TGL/SAPEC Líquidos", "12:30", "9,5 m para IMO", "10,0 m para não-IMO", "fórmula de calado praticável"),
    },
    {
        "id": "repontos-direct-teporset-departure",
        "group": "Repontos, Marés e Prioridades",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Teporset saída",
        "question": "Saída da Teporset para o reponto das 20:03, a que horas marco?",
        "expected_summary": "Saída Teporset deve marcar 15 min antes e explicar reponto local.",
        "source": "core/operational_sources.py + Marcar_manobra_repontos_mare.txt",
        "expected_origin": "operational_tide_scheduling",
        "expected_tokens": ("15 min antes do reponto", "19:48", "reponto local acontece cerca de 15 min depois"),
    },
    {
        "id": "repontos-direct-teporset-generic",
        "group": "Repontos, Marés e Prioridades",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Teporset regra geral de reponto",
        "question": "Para manobrar no Teporset, tenho de acertar com o reponto de mare?",
        "expected_summary": "Pergunta genérica deve devolver entrada por origem e saída 15 min antes.",
        "source": "core/operational_sources.py + Marcar_manobra_repontos_mare.txt",
        "expected_origin": "operational_tide_scheduling",
        "expected_tokens": ("Entrada de fora da Barra", "Fundeadouro Norte", "Saída: marcar cerca de 15 min antes", "reponto local acontece cerca de 15 min depois"),
    },
    {
        "id": "repontos-direct-secil-entry-departure-origin",
        "group": "Repontos, Marés e Prioridades",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "SECIL entrada/saída por origem",
        "question": "Como marco entrada e saída da SECIL por origem?",
        "expected_summary": "Pergunta composta deve responder entradas e saídas sem cair em timeout ou só saída.",
        "source": "core/operational_sources.py + IT-009_Secil.txt",
        "expected_origin": "secil_reponto_rule",
        "expected_tokens": ("Entradas para a SECIL", "30-45 min antes do reponto", "45 min a 1 h", "Saídas da SECIL", "15 minutos antes do reponto"),
    },
    {
        "id": "repontos-direct-lisnave-doca21-departure",
        "group": "Repontos, Marés e Prioridades",
        "risk": "Critico",
        "mode": "Automatico",
        "runner": "direct_operational",
        "label": "Lisnave Doca 21 saída",
        "question": "Saída da Doca 21 da Lisnave para a preia-mar das 20:03, a que horas marco?",
        "expected_summary": "Saída Doca 21/22 Lisnave deve marcar 2h antes da preia-mar.",
        "source": "core/operational_sources.py + IT-014_Lisnave.txt",
        "expected_origin": "operational_tide_scheduling",
        "expected_tokens": ("Docas 21/22", "2 horas antes da preia-mar", "18:03"),
    },
    {
        "id": "route-order-north-south",
        "group": "Conversas a testar manualmente",
        "risk": "Alto",
        "mode": "Manual guiado",
        "runner": "manual",
        "label": "Ordem dos cais por canal",
        "question": "Qual a ordem dos cais de entrada pelo Canal Norte e pelo Canal Sul?",
        "expected_summary": "Tem de responder pela fonte de ordem dos cais, separando entrada/saida e Norte/Sul.",
        "source": "knowledge/Ordem_Cais_*.txt",
        "expected_tokens": (),
    },
    {
        "id": "reponto-matrix",
        "group": "Conversas a testar manualmente",
        "risk": "Alto",
        "mode": "Manual guiado",
        "runner": "manual",
        "label": "Marcacoes a reponto",
        "question": "Quando marco uma saida da Doca 22 da Lisnave e uma entrada para Tanquisado?",
        "expected_summary": "Deve combinar a matriz de marcacoes com as regras de cais, sem inventar mares.",
        "source": "knowledge/Marcar_manobra_repontos_mare.txt",
        "expected_tokens": (),
    },
]


def berth_capacity_test_matrix() -> list[dict]:
    """Return berth-capacity rules that must remain visible in admin QA."""
    source = "knowledge/berth_profiles.json + knowledge/companions + domain/berth_layout.py + tests/test_berth_layout.py"

    def vessel(identifier: str, name: str, berth: str, loa_m: str | None = None) -> dict:
        payload = {"id": identifier, "vessel_name": name, "berth_label": berth}
        if loa_m is not None:
            payload["vessel_loa_m"] = loa_m
        return payload

    def case(
        identifier: str,
        group: str,
        label: str,
        case_text: str,
        expected: str,
        *,
        occupants: list[dict] | None = None,
        target_berth: str = "",
        target_loa_m: str = "",
        expected_conflict: bool | None = None,
        expected_conflict_id: str = "",
        expected_occupied_slots: int | None = None,
    ) -> dict:
        initial_state = ", ".join(
            f"{item.get('vessel_name')} em {item.get('berth_label')} ({item.get('vessel_loa_m', 'LOA desconhecido')} m)"
            for item in occupants or []
        ) or "Sem navios em porto no terminal testado."
        target = f"{target_berth} · LOA {target_loa_m} m" if target_berth else "Contagem de ocupação"
        return {
            "id": identifier,
            "group": group,
            "risk": "Critico",
            "label": label,
            "case": case_text,
            "initial_state": initial_state,
            "target": target,
            "expected": expected,
            "source": source,
            "occupants": occupants or [],
            "target_berth": target_berth,
            "target_loa_m": target_loa_m,
            "expected_conflict": expected_conflict,
            "expected_conflict_id": expected_conflict_id,
            "expected_occupied_slots": expected_occupied_slots,
        }

    return [
        case(
            "autoeuropa-two-small",
            "Autoeuropa",
            "Autoeuropa permite 2 navios abaixo de 230 m",
            "Cais 10 ocupado por 180 m; Cais 11 recebe outro 180 m.",
            "Sem conflito: Cais 10 e Cais 11 podem estar ambos ocupados quando nenhum navio chega a 230 m.",
            occupants=[vessel("auto-10", "Ro-Ro 180 C10", "Cais 10 / Autoeuropa", "180")],
            target_berth="Cais 11 / Autoeuropa",
            target_loa_m="180",
            expected_conflict=False,
        ),
        case(
            "autoeuropa-target-230-exclusive",
            "Autoeuropa",
            "Autoeuropa bloqueia navio novo a partir de 230 m",
            "Cais 10 ocupado por 180 m; tentar aprovar 230 m no Cais 11.",
            "Conflito: o novo navio com LOA >= 230 m precisa da Autoeuropa livre.",
            occupants=[vessel("auto-10", "Ro-Ro 180 C10", "Cais 10 / Autoeuropa", "180")],
            target_berth="Cais 11 / Autoeuropa",
            target_loa_m="230",
            expected_conflict=True,
            expected_conflict_id="auto-10",
        ),
        case(
            "autoeuropa-existing-230-exclusive",
            "Autoeuropa",
            "Autoeuropa bloqueia quando o navio em porto tem 230 m",
            "Cais 10 ocupado por 230 m; tentar aprovar 180 m no Cais 11.",
            "Conflito: um Ro-Ro de 230 m ou mais fica sozinho no terminal.",
            occupants=[vessel("auto-large", "Ro-Ro 230 C10", "Cais 10 / Autoeuropa", "230")],
            target_berth="Cais 11 / Autoeuropa",
            target_loa_m="180",
            expected_conflict=True,
            expected_conflict_id="auto-large",
        ),
        case(
            "autoeuropa-unknown-loa-conservative",
            "Autoeuropa",
            "Autoeuropa fica conservadora sem LOA do ocupante",
            "Cais 10 ocupado sem LOA registado; tentar aprovar 180 m no Cais 11.",
            "Conflito: sem LOA do navio em porto, não se assume que há espaço para segundo navio.",
            occupants=[vessel("auto-unknown", "Ro-Ro sem LOA", "Cais 10 / Autoeuropa")],
            target_berth="Cais 11 / Autoeuropa",
            target_loa_m="180",
            expected_conflict=True,
            expected_conflict_id="auto-unknown",
        ),
        case(
            "autoeuropa-two-229-allowed",
            "Autoeuropa",
            "Autoeuropa não aplica folga extra abaixo de 230 m",
            "Cais 10 ocupado por 229 m; tentar aprovar 229 m no Cais 11.",
            "Sem conflito: a regra operacional da Autoeuropa permite dois navios abaixo de 230 m, sem folga adicional de 30 m.",
            occupants=[vessel("auto-10", "Ro-Ro 229 C10", "Cais 10 / Autoeuropa", "229")],
            target_berth="Cais 11 / Autoeuropa",
            target_loa_m="229",
            expected_conflict=False,
        ),
        case(
            "tms1-230-c4-spans-c5",
            "TMS 1",
            "TMS 1 ocupa mais do que um cais por LOA",
            "Navio de 230 m no Cais 4; tentar usar o Cais 5.",
            "Conflito: o navio longo ocupa Cais 4 + Cais 5.",
            occupants=[vessel("tms1-c4", "TMS1 230 C4", "TMS 1 - Cais 4", "230")],
            target_berth="TMS 1 - Cais 5",
            target_loa_m="100",
            expected_conflict=True,
            expected_conflict_id="tms1-c4",
        ),
        case(
            "tms1-230-c4-allows-c6",
            "TMS 1",
            "TMS 1 liberta cais sem sobreposição física",
            "Navio de 230 m no Cais 4; tentar usar Cais 6 com 120 m.",
            "Sem conflito: Cais 6 fica fora do span Cais 4 + Cais 5.",
            occupants=[vessel("tms1-c4", "TMS1 230 C4", "TMS 1 - Cais 4", "230")],
            target_berth="TMS 1 - Cais 6",
            target_loa_m="120",
            expected_conflict=False,
        ),
        case(
            "tms1-target-230-c5-spans-c6",
            "TMS 1",
            "TMS 1 usa a esquerda se a direita está ocupada",
            "Cais 6 ocupado por 120 m; tentar aprovar 230 m no Cais 5.",
            "Sem conflito: como a direita está ocupada, o navio usa Cais 4 + Cais 5.",
            occupants=[vessel("tms1-c6", "TMS1 120 C6", "TMS 1 - Cais 6", "120")],
            target_berth="TMS 1 - Cais 5",
            target_loa_m="230",
            expected_conflict=False,
        ),
        case(
            "tms1-target-120-c5-does-not-span-c6",
            "TMS 1",
            "TMS 1 aceita navio curto no cais atribuído",
            "Cais 6 ocupado por 120 m; tentar aprovar 120 m no Cais 5.",
            "Sem conflito: 120 m fica dentro do Cais 5.",
            occupants=[vessel("tms1-c6", "TMS1 120 C6", "TMS 1 - Cais 6", "120")],
            target_berth="TMS 1 - Cais 5",
            target_loa_m="120",
            expected_conflict=False,
        ),
        case(
            "tms1-c7-100-spans-c6-not-c8",
            "TMS 1",
            "TMS 1 Cais 7 usa Cais 6 e não Cais 8",
            "Navio de 100 m no Cais 7; tentar usar Cais 8.",
            "Sem conflito: o Cais 8 é isolado e não serve de continuação ao Cais 7.",
            occupants=[vessel("tms1-c7", "TMS1 100 C7", "TMS 1 - Cais 7", "100")],
            target_berth="TMS 1 - Cais 8",
            target_loa_m="80",
            expected_conflict=False,
        ),
        case(
            "tms1-c7-left-side-occupied",
            "TMS 1",
            "TMS 1 bloqueia Cais 7 grande se o lado esquerdo está ocupado",
            "Cais 6 ocupado por 80 m; tentar aprovar 100 m no Cais 7.",
            "Conflito: Cais 7 precisa do Cais 6 para este LOA, porque o Cais 8 é isolado.",
            occupants=[vessel("tms1-c6", "TMS1 80 C6", "TMS 1 - Cais 6", "80")],
            target_berth="TMS 1 - Cais 7",
            target_loa_m="100",
            expected_conflict=True,
            expected_conflict_id="tms1-c6",
        ),
        case(
            "tms1-c7-610-capacity",
            "TMS 1",
            "TMS 1 Cais 7 não excede o lado esquerdo disponível",
            "Tentar aprovar 610 m no Cais 7.",
            "Conflito por capacidade: Cais 4 a Cais 7 somam 605 m e o Cais 8 não entra como continuação.",
            target_berth="TMS 1 - Cais 7",
            target_loa_m="610",
            expected_conflict=True,
            expected_conflict_id="__berth_capacity__",
        ),
        case(
            "tms1-left-boundary-blocked",
            "TMS 1",
            "TMS 1 bloqueia Cais 4 se a direita está ocupada",
            "Cais 5 ocupado; tentar aprovar 230 m no Cais 4.",
            "Conflito: o TMS1 já não tem Cais 3, por isso o Cais 4 não tem lado esquerdo disponível.",
            occupants=[vessel("tms1-c5", "TMS1 100 C5", "TMS 1 - Cais 5", "100")],
            target_berth="TMS 1 - Cais 4",
            target_loa_m="230",
            expected_conflict=True,
            expected_conflict_id="tms1-c5",
        ),
        case(
            "tms1-right-and-left-occupied-blocked",
            "TMS 1",
            "TMS 1 bloqueia se direita e esquerda estão ocupadas",
            "Cais 4 e Cais 6 ocupados; tentar aprovar 230 m no Cais 5.",
            "Conflito: não há sequência contígua livre para acomodar o navio.",
            occupants=[
                vessel("tms1-c4", "TMS1 100 C4", "TMS 1 - Cais 4", "100"),
                vessel("tms1-c6", "TMS1 100 C6", "TMS 1 - Cais 6", "100"),
            ],
            target_berth="TMS 1 - Cais 5",
            target_loa_m="230",
            expected_conflict=True,
            expected_conflict_id="tms1-c6",
        ),
        case(
            "tms1-30m-clearance-blocked",
            "TMS 1",
            "TMS 1 aplica folga mínima de 30 m",
            "Cais 6 ocupado por 170 m; tentar aprovar 330 m no Cais 4.",
            "Conflito: Cais 4 + 5 e Cais 6 somam 525 m, mas 330 + 30 + 170 exige 530 m.",
            occupants=[vessel("tms1-c6", "TMS1 170 C6", "TMS 1 - Cais 6", "170")],
            target_berth="TMS 1 - Cais 4",
            target_loa_m="330",
            expected_conflict=True,
            expected_conflict_id="tms1-c6",
        ),
        case(
            "tms1-cais8-limit",
            "TMS 1",
            "Cais 8 aceita só um navio até 215 m",
            "Tentar aprovar navio de 216 m no TMS 1 - Cais 8.",
            "Conflito por capacidade física do Cais 8.",
            target_berth="TMS 1 - Cais 8",
            target_loa_m="216",
            expected_conflict=True,
            expected_conflict_id="__berth_capacity__",
        ),
        case(
            "tms1-three-large-with-cais8",
            "TMS 1",
            "TMS 1 permite 3 navios grandes incluindo Cais 8",
            "230 m no Cais 4 e 230 m no Cais 6; tentar 215 m no Cais 8.",
            "Sem conflito: o máximo é 3 navios grandes quando o terceiro fica no Cais 8, que pertence ao TMS 1 mas é isolado.",
            occupants=[
                vessel("tms1-c4", "TMS1 230 C4", "TMS 1 - Cais 4", "230"),
                vessel("tms1-c6", "TMS1 230 C6", "TMS 1 - Cais 6", "230"),
            ],
            target_berth="TMS 1 - Cais 8",
            target_loa_m="215",
            expected_conflict=False,
        ),
        case(
            "tms1-two-large-allow-small-cais8",
            "TMS 1",
            "TMS 1 permite Cais 8 curto se livre",
            "230 m no Cais 4 e 230 m no Cais 6; tentar 180 m no Cais 8.",
            "Sem conflito: o limite de 3 grandes não se aplica a navio abaixo de 200 m.",
            occupants=[
                vessel("tms1-c4", "TMS1 230 C4", "TMS 1 - Cais 4", "230"),
                vessel("tms1-c6", "TMS1 230 C6", "TMS 1 - Cais 6", "230"),
            ],
            target_berth="TMS 1 - Cais 8",
            target_loa_m="180",
            expected_conflict=False,
        ),
        case(
            "tms2-230-a-spans-b",
            "TMS 2",
            "TMS 2 230 m ocupa posição adjacente",
            "Posição A ocupada por 230 m; tentar 230 m na Posição B.",
            "Conflito: com quatro posições de referência, cada posição tem 180,75 m e o navio de 230 m ocupa A + B.",
            occupants=[vessel("tms2-a", "TMS2 230 A", "TMS 2 - Posição A", "230")],
            target_berth="TMS 2 - Posição B",
            target_loa_m="230",
            expected_conflict=True,
            expected_conflict_id="tms2-a",
        ),
        case(
            "tms2-300-a-spans-b",
            "TMS 2",
            "TMS 2 ocupa posições adjacentes por LOA",
            "Navio de 300 m na Posição A; tentar usar a Posição B.",
            "Conflito: o navio longo ocupa A + B.",
            occupants=[vessel("tms2-a", "TMS2 300 A", "TMS 2 - Posição A", "300")],
            target_berth="TMS 2 - Posição B",
            target_loa_m="100",
            expected_conflict=True,
            expected_conflict_id="tms2-a",
        ),
        case(
            "tms2-300-a-allows-c",
            "TMS 2",
            "TMS 2 deixa livre posição sem sobreposição",
            "Navio de 300 m na Posição A; tentar usar a Posição C.",
            "Sem conflito: A + B ficam ocupadas e C continua avaliável.",
            occupants=[vessel("tms2-a", "TMS2 300 A", "TMS 2 - Posição A", "300")],
            target_berth="TMS 2 - Posição C",
            target_loa_m="100",
            expected_conflict=False,
        ),
        case(
            "tms2-right-occupied-use-left",
            "TMS 2",
            "TMS 2 prefere direita mas usa esquerda se necessário",
            "Posição C ocupada; tentar aprovar 300 m na Posição B.",
            "Sem conflito: como a direita está ocupada, o navio usa Posição A + Posição B.",
            occupants=[vessel("tms2-c", "TMS2 100 C", "TMS 2 - Posição C", "100")],
            target_berth="TMS 2 - Posição B",
            target_loa_m="300",
            expected_conflict=False,
        ),
        case(
            "tms2-right-and-left-occupied-blocked",
            "TMS 2",
            "TMS 2 bloqueia se direita e esquerda estão ocupadas",
            "Posições A e C ocupadas; tentar aprovar 300 m na Posição B.",
            "Conflito: não há sequência contígua livre para acomodar o navio.",
            occupants=[
                vessel("tms2-a", "TMS2 100 A", "TMS 2 - Posição A", "100"),
                vessel("tms2-c", "TMS2 100 C", "TMS 2 - Posição C", "100"),
            ],
            target_berth="TMS 2 - Posição B",
            target_loa_m="300",
            expected_conflict=True,
            expected_conflict_id="tms2-c",
        ),
        case(
            "tms2-500-b-spans-all",
            "TMS 2",
            "TMS 2 central com 500 m ocupa três posições",
            "Navio de 500 m na Posição B; tentar usar a Posição C.",
            "Conflito: para incluir B e acomodar 500 m, o span cobre B + C + D.",
            occupants=[vessel("tms2-b", "TMS2 500 B", "TMS 2 - Posição B", "500")],
            target_berth="TMS 2 - Posição C",
            target_loa_m="100",
            expected_conflict=True,
            expected_conflict_id="tms2-b",
        ),
        case(
            "tms2-750-capacity",
            "TMS 2",
            "TMS 2 bloqueia LOA acima do comprimento total",
            "Tentar aprovar 750 m no TMS 2.",
            "Conflito por capacidade: o terminal tem 723 m úteis de referência.",
            target_berth="TMS 2 - Posição B",
            target_loa_m="750",
            expected_conflict=True,
            expected_conflict_id="__berth_capacity__",
        ),
        case(
            "tms2-four-150-allowed",
            "TMS 2",
            "TMS 2 permite quatro navios de 150 m",
            "Posições A, B e C com 150 m; tentar 150 m na Posição D.",
            "Sem conflito: quatro navios de 150 m cabem no comprimento total com folgas de 30 m.",
            occupants=[
                vessel("tms2-a", "TMS2 150 A", "TMS 2 - Posição A", "150"),
                vessel("tms2-b", "TMS2 150 B", "TMS 2 - Posição B", "150"),
                vessel("tms2-c", "TMS2 150 C", "TMS 2 - Posição C", "150"),
            ],
            target_berth="TMS 2 - Posição D",
            target_loa_m="150",
            expected_conflict=False,
        ),
        case(
            "tms2-four-170-blocked",
            "TMS 2",
            "TMS 2 bloqueia quatro navios de 170 m",
            "Posições A, B e C com 170 m; tentar 170 m na Posição D.",
            "Conflito por comprimento total e folgas: quatro navios de 170 m não passam nos 723 m.",
            occupants=[
                vessel("tms2-a", "TMS2 170 A", "TMS 2 - Posição A", "170"),
                vessel("tms2-b", "TMS2 170 B", "TMS 2 - Posição B", "170"),
                vessel("tms2-c", "TMS2 170 C", "TMS 2 - Posição C", "170"),
            ],
            target_berth="TMS 2 - Posição D",
            target_loa_m="170",
            expected_conflict=True,
            expected_conflict_id="tms2-a",
        ),
        case(
            "occupancy-tms2-middle-500",
            "Contagem de slots",
            "Ocupação conta TMS 2 central de 500 m como 3 slots",
            "Snapshot com navio de 500 m na Posição B.",
            "A ocupação deve contar A + B + C como ocupados.",
            occupants=[vessel("tms2-b", "TMS2 500 B", "TMS 2 - Posição B", "500")],
            expected_occupied_slots=3,
        ),
        case(
            "occupancy-tms1-c7-overflow",
            "Contagem de slots",
            "Ocupação conta Cais 7 de 100 m como Cais 6 + Cais 7",
            "Snapshot com navio de 100 m no Cais 7.",
            "A ocupação deve contar dois slots físicos no TMS 1, sem ocupar o Cais 8.",
            occupants=[vessel("tms1-c7", "TMS1 100 C7", "TMS 1 - Cais 7", "100")],
            expected_occupied_slots=2,
        ),
        case(
            "occupancy-autoeuropa-large",
            "Contagem de slots",
            "Ocupação conta Autoeuropa >=230 m como 2 slots",
            "Snapshot com Ro-Ro de 230 m no Cais 10.",
            "A ocupação deve contar Cais 10 + Cais 11.",
            occupants=[vessel("auto-large", "Ro-Ro 230 C10", "Cais 10 / Autoeuropa", "230")],
            expected_occupied_slots=2,
        ),
    ]
